name: noc-convert
version: '1.0.0'
summary: Fast, no-cloud bulk image converter.
description: |
  Bulk Image Converter (NoCloud). The easy way to batch convert all your images.
grade: stable
confinement: strict
base: core24
icon: snap/gui/icon.png
title: NoCloud Bulk Image Converter
website: https://andre-i.eu
issues: https://github.com/goto-eof
source-code: https://github.com/goto-eof/noc-convert
donation: https://github.com/sponsors/goto-eof
contact: https://andre-i.eu/#contactme
compression: lzo
license: CC-BY-NC-4.0
apps:
  noc-convert:
    command: executor
    extensions: [ gnome ]
    plugs:
      - browser-support
      - home
      - removable-media
      - unity7
      - wayland
      - x11
platforms:
  amd64:
    build-on: [ amd64 ]
    build-for: [ amd64 ]
  arm64:
    build-on: [ arm64 ]
    build-for: [ arm64 ]
parts:
  wrapper:
    plugin: dump
    source: snap/local
    source-type: local
  application:
    plugin: maven
    source: .
    build-packages:
      - openjdk-21-jdk
      - maven
      - sed
    override-build: |
      
      getproxy () {
      host=$(echo "$1" | sed -E 's|https?://([^:/]*):?[0-9]*/?|\1|')
      port=$(echo "$1" | sed -E 's|https?://[^:/]*:?([0-9]*)/?|\1|')
      }
      
      echo "Starting to build NoCloud Bulk Image Converter at $(date)"
      START_TIME=$(date +%s)
      echo "Start building NoCloud Bulk Image Converter at $(date)"
      
      set -eux
      JLINK_JDK_PATH="/usr/lib/jvm/java-21-openjdk-$(dpkg-architecture -q DEB_BUILD_MULTIARCH)"
      REQUIRED_MODULES="java.base,java.desktop,java.net.http,java.management,java.security.jgss,java.xml,java.logging,jdk.crypto.ec,java.security.sasl"
      
      echo "Creating custom JRE runtime with the following modules: $REQUIRED_MODULES"
      
      /usr/bin/jlink \
        --add-modules $REQUIRED_MODULES \
        --output "$SNAPCRAFT_PART_INSTALL"/usr/lib/jvm/custom-jre \
        --compress=2 \
        --no-header-files \
        --no-man-pages \
        --strip-debug
      
      http=""
      https=""
      
      if [ -n "${http_proxy:-}" ]; then
          getproxy "$http_proxy"
          http="-Dhttp.proxyHost=$host -Dhttp.proxyPort=$port"
      fi
      
      if [ -n "${https_proxy:-}" ]; then
          getproxy "$https_proxy"
          https="-Dhttps.proxyHost=$host -Dhttps.proxyPort=$port"
      fi

      export MAVEN_OPTS="$http $https"
      
      mvn clean install -DskipTests
      
      APP_JAR_NAME="fromgtog.jar" 
      APP_JAR_PATH="$SNAPCRAFT_PART_BUILD/target/$APP_JAR_NAME"
      
      if [ ! -f "$APP_JAR_PATH" ]; then
          echo "ERROR: jar not found in $APP_JAR_PATH"
          exit 1
      fi

      mkdir -p "$SNAPCRAFT_PART_INSTALL"/jar
      echo "Directory created: $SNAPCRAFT_PART_INSTALL/jar"

      echo "Copying $APP_JAR_NAME in $SNAPCRAFT_PART_INSTALL/jar/noc-convert.jar"
      cp "$APP_JAR_PATH" "$SNAPCRAFT_PART_INSTALL"/jar/noc-convert.jar
      
      echo "custom JRE runtime created in $SNAPCRAFT_PART_INSTALL/usr/lib/jvm/custom-jre"
      rm -rf "$JLINK_JDK_PATH"
      echo "temporary JDK removed."
      
      echo "Finished building FromGtoG at $(date)"
      END_TIME=$(date +%s)
      echo "Total time: $((${END_TIME} - ${START_TIME})) seconds"
    stage-packages:
      - libgtk-3-0
      - xdg-utils
    override-prime: |
      snapcraftctl prime

