name: Create MacOS ARM64 PKG file

on:
  push:
    tags:
      - '*'

jobs:
  build_jar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure JDK (Linux)
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '25'

      - name: Build JAR with Maven
        run: |
          mvn clean verify package
          mkdir -p target/lib
          mvn dependency:copy-dependencies -DoutputDirectory=target/lib

      - name: Upload Artifact (JAR and resources)
        uses: actions/upload-artifact@v4
        with:
          name: application-files
          path: |
            target/noc-convert.jar
            target/lib/
            resources/

  create_pkg_arm:
    runs-on: macos-14
    permissions:
      contents: write
    needs: build_jar
    steps:
      - uses: actions/checkout@v4

      - name: Define release version
        id: set_version
        run: |
          echo "RELEASE_TAG=${GITHUB_REF_NAME}" >> $GITHUB_ENV
          echo "Release Tag set on: ${GITHUB_REF_NAME}"

      - name: Download Artifact (JAR and resources)
        uses: actions/download-artifact@v4
        with:
          name: application-files
          path: downloaded-files

      - name: Configure JDK for macOS ARM
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '25'
          architecture: arm64

      - name: Create PKG file with jpackage (ARM)
        run: |
          INPUT_PATH="downloaded-files/target"
          OUTPUT_PATH="executable"
          MAIN_JAR="noc-convert.jar"
          ICON_PATH="downloaded-files/resources/icon-macos.icns"

          mkdir -p "$OUTPUT_PATH"

          jpackage \
            --input "$INPUT_PATH" \
            --dest "$OUTPUT_PATH" \
            --name "noc-convert" \
            --vendor "Andrei Dodu" \
            --app-version "$RELEASE_TAG" \
            --main-jar "$MAIN_JAR" \
            --main-class org.andreidodu.nocconvert.Main \
            --icon "$ICON_PATH" \
            --type pkg \
            --java-options "--add-opens java.desktop/javax.imageio.spi=ALL-UNNAMED -Dlog4j2.disable.jmx=true -Dlog4j2.formatMsgNoLookups=true -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true" \
            --add-modules java.base,java.desktop,java.logging,java.management,java.naming,jdk.management \
            --verbose

      - name: Zip PKG file (ARM)
        run: |
          PKG_FILE=$(ls executable/*.pkg | head -n 1)
          ZIP_NAME="${{ github.event.repository.name }}-MacOS-${{ github.ref_name }}-arm64-Installer.zip"
          zip -j "$ZIP_NAME" "$PKG_FILE"

      - name: Release on GitHub
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ${{ github.event.repository.name }}-MacOS-${{ github.ref_name }}-arm64-Installer.zip
